Repository andela/titan-dev-ah-frontend, pull requests merged in 2019-05, with the labels that each got.

#37 163518646 View and Edit Profile
  .babelrc
  .gitignore
  .sample.env
  README.md
  enzyme.config.js
  html-css/index.html
  package.json
  public/index.html
  src/__tests__/App.test.js
  src/__tests__/__actions__/authActions.test.js
  src/__tests__/__actions__/resetPasswordActions.test.js
  src/__tests__/__actions__/socialAuthActions.test.js
  src/__tests__/__actions__/updatePasswordActions.test.js
  src/__tests__/__actions__/userProfile.test.js
  src/__tests__/__components__/Dialog/Dialog.test.js
  src/__tests__/__components__/Inputs/TextInput.test.js
  src/__tests__/__components__/Messages/ErrorMessage.test.js
  src/__tests__/__components__/Messages/Message.test.js
  src/__tests__/__components__/Messages/SuccessMessage.test.js
  src/__tests__/__components__/Spinner/Loading.test.js
  src/__tests__/__helpers__/helpers.test.js
  src/__tests__/__reducers__/userReducers.test.js
  src/__tests__/__views__/EditProfile.test.js
  src/__tests__/__views__/Profile.test.js
  src/__tests__/__views__/Settings.test.js
  src/__tests__/testData.js
  src/assets/img/403.png
  src/assets/img/404error.png
  src/assets/img/circle-loading.gif
  src/assets/img/defaultImage.png
  src/components/common/AppBars/navBar.js
  src/components/common/Dialog/Dialog.js
  src/components/common/Inputs/input.js
  src/components/common/Message/message.js
  src/components/common/Message/success.js
  src/components/common/Spinner/Loading.js
  src/helpers/helpers.js
  src/index.js
  src/redux/actionTypes.js
  src/redux/actions/authActions.js
  src/redux/actions/index.js
  src/redux/actions/profileActions.js
  src/redux/reducers/index.js
  src/redux/reducers/userReducer.js
  src/redux/store.js
  src/style/base/_button.scss
  src/styles/base/_button.scss
  src/styles/base/_input.scss
  src/styles/base/_loading.scss
  src/styles/base/_message.scss
  src/styles/base/_on_off.scss
  src/styles/main.scss
  src/styles/pages/_update-profile.scss
  src/styles/pages/_user-settings.scss
  src/utils/axios.js
  src/views/EditProfile.js
  src/views/Home.js
  src/views/Profile.js
  src/views/Settings.js
  src/views/routes/MainRoutes.js
Labels: enhancement

#55 #163518655 Share the article via email, facebook, and twitter
  src/__tests__/__components__/Link/Social.test.js
  src/assets/img/paper-plane.svg
  src/components/common/Link/Social.js
  src/styles/pages/_article.scss
  src/views/ReadArticle.js
Labels: Needs a review

#51 #163518655 Add following functionality on readArticle page
  src/__tests__/__actions__/following.test.js
  src/__tests__/__mocks__/testData.js
  src/__tests__/__reducers__/authReducers.test.js
  src/__tests__/__reducers__/following.test.js
  src/__tests__/__views__/ReadArticle.test.js
  src/redux/actionTypes.js
  src/redux/actions/followingActions.js
  src/redux/reducers/followingReducer.js
  src/redux/reducers/index.js
  src/styles/base/_button.scss
  src/styles/pages/_article.scss
  src/views/ReadArticle.js
Labels: Needs approval

#43 #165427095 Design the notification wrapper, view, delete notifications
  package.json
  src/__tests__/__actions__/authActions.test.js
  src/__tests__/__actions__/createArticle.test.js
  src/__tests__/__actions__/notificationAction.test.js
  src/__tests__/__actions__/resetPasswordActions.test.js
  src/__tests__/__actions__/socialAuthActions.test.js
  src/__tests__/__actions__/updatePasswordActions.test.js
  src/__tests__/__actions__/userProfile.test.js
  src/__tests__/__components__/AppBars/NavBar.test.js
  src/__tests__/__components__/Buttons/BasicButton.test.js
  src/__tests__/__components__/Buttons/FormButton.test.js
  src/__tests__/__components__/Buttons/SocialButton.test.js
  src/__tests__/__components__/tags.test.js
  src/__tests__/__reducers__/authReducers.test.js
  src/__tests__/__reducers__/createArticle.test.js
  src/__tests__/__reducers__/notificationReducer.test.js
  src/__tests__/__reducers__/resetPasswordReducers.test.js
  src/__tests__/__reducers__/socialAuthReducers.test.js
  src/__tests__/__reducers__/updatePasswordReducers.test.js
  src/__tests__/__utils__/helperFunctions.test.js
  src/__tests__/__utils__/validator.test.js
  src/__tests__/__views__/EditArticle.test.js
  src/__tests__/__views__/Login.test.js
  src/__tests__/__views__/NewArticle.test.js
  src/__tests__/__views__/Profile.test.js
  src/__tests__/__views__/ResetPassword.test.js
  src/__tests__/__views__/SearchRetuls.test.js
  src/__tests__/__views__/Settings.test.js
  src/__tests__/__views__/SocialAuth.test.js
  src/__tests__/__views__/UpdatePassword.test.js
  src/__tests__/routes.test.js
  src/assets/icons/check.svg
  src/assets/icons/checked.svg
  src/assets/icons/checkmark.svg
  src/assets/icons/circle.svg
  src/assets/icons/close.svg
  src/assets/icons/down-arrow.svg
  src/assets/icons/fire.svg
  src/assets/icons/notification.svg
  src/assets/icons/search.svg
  src/assets/icons/tick.svg
  src/components/common/AppBars/Navbar.js
  src/components/common/AppBars/navBar.js
  src/components/common/Logo/Thumbnail.js
  src/redux/actionTypes.js
  src/redux/actions/notificationActions.js
  src/redux/reducers/index.js
  src/redux/reducers/notificationReducer.js
  src/styles/base/_base.scss
  src/styles/layout/_nav-bar.scss
  src/views/EditArticle.js
  src/views/ReadArticle.js
  src/views/routes/MainRoutes.js
Labels: Needs approval

#60 163518666 Liking a comment
  src/__tests__/__actions__/commentsActions.test.js
  src/__tests__/__reducers__/commentsReducer.test.js
  src/__tests__/__views__/Comments.test.js
  src/__tests__/__views__/ReadArticle.test.js
  src/redux/actionTypes.js
  src/redux/actions/commentActions.js
  src/redux/reducers/CommentReducer.js
  src/styles/layout/_card-comments.scss
  src/views/Comments.js
  src/views/ReadArticle.js
Labels: Needs a review

#59 #163518648 Rate Article
  package.json
  src/__tests__/__actions__/articleActionCreator.test.js
  src/__tests__/__actions__/ratingActions.test.js
  src/__tests__/__components__/Cards/mainCard.test.js
  src/__tests__/__components__/RatingForm/RatingForm.test.js
  src/__tests__/__helpers__/bodyParser.test.js
  src/__tests__/__mocks__/testData.js
  src/__tests__/__reducers__/ratingReducers.test.js
  src/__tests__/__reducers__/readArticle.test.js
  src/__tests__/__views__/Comments.test.js
  src/__tests__/__views__/Home.test.js
  src/assets/img/star.svg
  src/assets/img/star_filled.svg
  src/components/common/AppBars/Navbar.js
  src/components/common/Buttons/RatingButton.js
  src/components/common/RatingForm/RatingForm.js
  src/redux/actionTypes.js
  src/redux/actions/articleActionCreator.js
  src/redux/actions/ratingActions.js
  src/redux/reducers/index.js
  src/redux/reducers/ratingReducer.js
  src/styles/pages/_article.scss
  src/utils/helpers/bodyParser.js
  src/views/ReadArticle.js
Labels: Needs a review

#50 #163518661 create bookmark articles component
  package-lock.json
  src/__tests__/__actions__/bookmarkActions.test.js
  src/__tests__/__actions__/registrationActions.test.js
  src/__tests__/__components__/AppBars/NavBar.test.js
  src/__tests__/__components__/Bookmark.test.js
  src/__tests__/__components__/Cards/mainCard.test.js
  src/__tests__/__components__/Logo/index.test.js
  src/__tests__/__helpers__/validators.test.js
  src/__tests__/__reducers__/authReducers.test.js
  src/__tests__/__reducers__/bookmarkReducers.test.js
  src/__tests__/__reducers__/following.test.js
  src/__tests__/__reducers__/registrationReducers.test.js
  src/__tests__/__views__/Bookmark.test.js
  src/__tests__/__views__/Comments.test.js
  src/__tests__/__views__/ReadArticle.test.js
  src/__tests__/__views__/SignUp.test.js
  src/components/common/Bookmarks.js
  src/components/common/Cards/AnimatedCard.js
  src/components/common/Cards/main.js
  src/redux/actionTypes.js
  src/redux/actions/bookmarkActions.js
  src/redux/reducers/bookmarkReducers.js
  src/redux/reducers/index.js
  src/styles/pages/_article.scss
  src/utils/axios.js
  src/views/Bookmark.js
  src/views/ReadArticle.js
  src/views/SearchResults.js
Labels: Needs a review
